server:
  port: 8189
  servlet:
    context-path: /market-core
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
integrations:
  cart-service:
    url: http://localhost:8190/market-carts/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000